Scheduler:
  Enable: false
  NextRun: 1989-12-27 00:00:00
  Command: NKAS
  SuccessInterval:
    value: 0
    display: hide
  FailureInterval:
    value: 120
    display: hide
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  PackageName:
    value: com_proximabeta_nikke
    option: [ com_proximabeta_nikke, com_gamamobi_nikke, ]
  ScreenshotMethod:
    value: DroidCast
    option: [ DroidCast, ]
  ControlMethod:
    value: minitouch
    option: [ minitouch, ]
  AdbRestart: false
  ScreenshotInterval: 0.5
Optimization:
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game ]
Reward:
  CollectSocialPoint: true
  CollectSpecialArenaPoint: true
Area:
  Difficulty:
    value: 'Level_1'
    option: [ 'Level_1', 'Level_2', 'Level_3','Level_4','Level_5' ]
  OnsetArea:
    value: A
    option: [ A, B, C ]
  EndingArea:
    value: A
    option: [ A, B, C ]
Overcome:
  OnlyToCompleteDailyMission: false
GeneralShop:
  enable: true
ArenaShop:
  enable: false
  priority: ''
RubbishShop:
  priority: ''
Notification:
  WhenDailyTaskCompleted: false
Event:
  Event_Name: ''
  Complete_Event: false
  Event:
    value: 'event_5'
    option: [ 'event_5' ]
  Part:
    value: 'story_1'
    option: [ 'story_1','story_2' ]
  Difficulty:
    value: 'normal'
    option: [ 'normal','hard' ]
Daily:
  EnhanceEquipment: false
Cookie:
   lip_user_name:
     value: ""
     valuetype: str
   lip_uid:
     value: ""
     valuetype: str
   lip_token:
     value: ""
     valuetype: str
   lip_openid:
     value: ""
     valuetype: str
   lip_expire_time:
     value: ""
     valuetype: str
   lip_picture_url:
     value: ""
     valuetype: str