# ==================== NKAS ====================

NKAS:
  - Emulator
  - Optimization
  - Notification

Restart:
  - Scheduler

# ==================== Reward ====================

Reward:
  - Scheduler
  - Reward

Destroy:
  - Scheduler

Commission:
  - Scheduler

Mailbox:
  - Scheduler

# ==================== Daily ====================
LIPass:
  - Scheduler

Daily:
  - Scheduler
  - Daily

MissionPass:
  - Scheduler

Liberation:
  - Scheduler

Conversation:
  - Scheduler

Shop:
  - Scheduler
  - GeneralShop
  - ArenaShop

RubbishShop:
  - Scheduler
  - RubbishShop

SimulationRoom:
  - Scheduler
  - Area

TribeTower:
  - Scheduler
  - Overcome

RookieArena:
  - Scheduler

Interception:
  - Scheduler

# ==================== Gift ====================

DailyGift:
  - Scheduler

WeeklyGift:
  - Scheduler

MonthlyGift:
  - Scheduler