Task:
  Commission:
    activate: true
    displayName: 委托
    name: Commission
    nextExecutionTime: 946656000
  Conversation:
    activate: true
    displayName: 咨询
    name: Conversation
    nextExecutionTime: 946656000
    nikkeList: [ ]
  Daily:
    activate: true
    displayName: 每日任务
    equipmentUpgrade: false
    name: Daily
    nextExecutionTime: 946656060
    nikkeUpgrade: true
  Destroy:
    activate: true
    displayName: 一举歼灭
    name: Destroy
    nextExecutionTime: 946656000
  Event:
    activate: true
    currentEvent: 2
    difficulty: 1
    displayName: 活动
    event: 1-1
    finishAllEvent: true
    historyEvent:
      - label: BOW-WOW PARADISE
        path: /event_2
        type: 0
        value: 2
      - label: Chainsaw Man
        path: /event_1
        type: 1
        value: 1
    name: Event
    nextExecutionTime: 946656000
    part: 2
  FreeStore:
    activate: true
    activate_arena_store: true
    activate_rubbish_store: true
    arena_product_list: ''
    rubbish_store_product_list: ''
    displayName: 商店
    name: FreeStore
    nextExecutionTime: 946656000
    rubbishStoreNextExecutionTime: 946656000
  Reward:
    activate: true
    arena: true
    displayName: 收获
    name: Reward
    nextExecutionTime: 946656000
    recordTwiceTime: 946656000
  RookieArena:
    activate: true
    displayName: 新人竞技场
    name: RookieArena
    nextExecutionTime: 946656000
    refresh_chance: '1'
    target: 1
    under: '0'
  SimulationRoom:
    activate: true
    area: '1'
    difficulty: '1'
    displayName: 模拟室
    end_area: '1'
    name: SimulationRoom
    nextExecutionTime: 946656000
  TribeTower:
    Elysion: true
    Missilis: true
    Pilgrim: true
    Tetra: true
    activate: true
    daily: true
    displayName: 企业塔
    name: TribeTower
    nextExecutionTime: 946656000
